package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"time"

	"github.com/cc-santiago-alvarez/go_inventory.git/graphql/generated"
	"github.com/cc-santiago-alvarez/go_inventory.git/models"
)

// CreatedAt is the resolver for the created_at field.
func (r *categoryResolver) CreatedAt(ctx context.Context, obj *models.Category) (*string, error) {
	t := obj.CreatedAt.Format(time.RFC3339)
	return &t, nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *categoryResolver) UpdatedAt(ctx context.Context, obj *models.Category) (*string, error) {
	t := obj.UpdatedAt.Format(time.RFC3339)
	return &t, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *categoryWithProductsResolver) CreatedAt(ctx context.Context, obj *models.CategoryWithProducts) (*string, error) {
	t := obj.CreatedAt.Format(time.RFC3339)
	return &t, nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *categoryWithProductsResolver) UpdatedAt(ctx context.Context, obj *models.CategoryWithProducts) (*string, error) {
	t := obj.UpdatedAt.Format(time.RFC3339)
	return &t, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input *generated.CategoryInput) (*models.Category, error) {
	return r.CategoryService.CreateCategory(ctx, *input.Name, *input.Description)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input *generated.CategoryInput) (*bool, error) {
	err := r.CategoryService.UpdateCategory(ctx, id, *input.Name, *input.Description)
	if err != nil {
		result := false
		return &result, err
	}
	result := true
	return &result, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (*bool, error) {
	err := r.CategoryService.DeleteCategory(ctx, id)
	if err != nil {
		result := false
		return &result, err
	}
	result := true
	return &result, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*models.Category, error) {
	categories, err := r.CategoryService.FindAllCategories(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*models.Category, len(categories))
	for i := range categories {
		result[i] = &categories[i]
	}
	return result, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id *string) (*models.Category, error) {
	return r.CategoryService.FindCategoryById(ctx, *id)
}

// CategoryWithProducts is the resolver for the categoryWithProducts field.
func (r *queryResolver) CategoryWithProducts(ctx context.Context, id *string) (*models.CategoryWithProducts, error) {
	return r.CategoryService.FindCategoryWithProducts(ctx, *id)
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// CategoryWithProducts returns generated.CategoryWithProductsResolver implementation.
func (r *Resolver) CategoryWithProducts() generated.CategoryWithProductsResolver {
	return &categoryWithProductsResolver{r}
}

type categoryResolver struct{ *Resolver }
type categoryWithProductsResolver struct{ *Resolver }
