package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"time"

	"github.com/cc-santiago-alvarez/go_inventory.git/graphql/generated"
	"github.com/cc-santiago-alvarez/go_inventory.git/models"
)

// Date is the resolver for the date field.
func (r *movementResolver) Date(ctx context.Context, obj *models.Movement) (string, error) {
	return obj.Date.Format(time.RFC3339), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *movementResolver) CreatedAt(ctx context.Context, obj *models.Movement) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// CreateMovement is the resolver for the createMovement field.
func (r *mutationResolver) CreateMovement(ctx context.Context, input models.CreateMovementRequest) (*models.Movement, error) {
	return r.MovementService.CreateMovement(ctx, input)
}

// Movements is the resolver for the movements field.
func (r *queryResolver) Movements(ctx context.Context) ([]*models.Movement, error) {
	movements, err := r.MovementService.FindAllMovements(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*models.Movement, len(movements))
	for i := range movements {
		result[i] = &movements[i]
	}
	return result, nil
}

// MovementsByProduct is the resolver for the movementsByProduct field.
func (r *queryResolver) MovementsByProduct(ctx context.Context, productID string) ([]*models.Movement, error) {
	movements, err := r.MovementService.FindMovementsByProductID(ctx, productID)
	if err != nil {
		return nil, err
	}
	result := make([]*models.Movement, len(movements))
	for i := range movements {
		result[i] = &movements[i]
	}
	return result, nil
}

// MovementsByType is the resolver for the movementsByType field.
func (r *queryResolver) MovementsByType(ctx context.Context, typeArg models.MovementType) ([]*models.Movement, error) {
	movements, err := r.MovementService.FindMovementsByType(ctx, typeArg)
	if err != nil {
		return nil, err
	}
	result := make([]*models.Movement, len(movements))
	for i := range movements {
		result[i] = &movements[i]
	}
	return result, nil
}

// MovementsByDateRange is the resolver for the movementsByDateRange field.
func (r *queryResolver) MovementsByDateRange(ctx context.Context, from string, to string) ([]*models.Movement, error) {
	fromTime, err := time.Parse(time.RFC3339, from)
	if err != nil {
		return nil, err
	}
	toTime, err := time.Parse(time.RFC3339, to)
	if err != nil {
		return nil, err
	}
	movements, err := r.MovementService.FindMovementsByDateRange(ctx, fromTime, toTime)
	if err != nil {
		return nil, err
	}
	result := make([]*models.Movement, len(movements))
	for i := range movements {
		result[i] = &movements[i]
	}
	return result, nil
}

// Movement returns generated.MovementResolver implementation.
func (r *Resolver) Movement() generated.MovementResolver { return &movementResolver{r} }

type movementResolver struct{ *Resolver }
