package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	"time"

	"github.com/cc-santiago-alvarez/go_inventory.git/graphql/generated"
	"github.com/cc-santiago-alvarez/go_inventory.git/models"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input *generated.ProductInput) (*models.Product, error) {
	return r.ProductService.CreateProduct(ctx, *input.Name, *input.Description, *input.Price, *input.Quantity, *input.CategoryID)
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input *generated.ProductInput) (*bool, error) {
	err := r.ProductService.UpdateProduct(ctx, id, *input.Name, *input.Description, *input.Price, *input.Quantity, *input.CategoryID)
	if err != nil {
		result := false
		return &result, err
	}
	result := true
	return &result, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (*bool, error) {
	err := r.ProductService.DeleteProduct(ctx, id)
	if err != nil {
		result := false
		return &result, err
	}
	result := true
	return &result, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *productResolver) CreatedAt(ctx context.Context, obj *models.Product) (*string, error) {
	t := obj.CreatedAt.Format(time.RFC3339)
	return &t, nil
}

// UpdatedAt is the resolver for the updated_at field.
func (r *productResolver) UpdatedAt(ctx context.Context, obj *models.Product) (*string, error) {
	t := obj.UpdatedAt.Format(time.RFC3339)
	return &t, nil
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*models.Product, error) {
	products, err := r.ProductService.FindAllProducts(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*models.Product, len(products))
	for i := range products {
		result[i] = &products[i]
	}
	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id *string) (*models.Product, error) {
	return r.ProductService.FindProductById(ctx, *id)
}

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

type productResolver struct{ *Resolver }
